### ISSUE TITLE
how do a test?

### ISSUE THREAD

**Issue by IvyGongoogle** [NoahApthorpe/ConvnetCellDetection#2]
hello, interesting at your repository. but how to test a simple image, And can you provide some images dataset and pre-trained model?
thank you very much!

**Comment by NoahApthorpe** [comment]
You can test your environment set up using the data in the data/example directory.  However, this does not contain enough data to train a useful network.  We are waiting to release our data until the experimentalists who collected it have published their results.

**Comment by IvyGongoogle** [comment]
@NoahApthorpe thankyou!
